extractor:
  name: sp
  num_kpt: 4000
  resize: [-1] 
  det_th: 0.00001
  

matcher:
  name: SG
  model_dir: ../weights/sg/sp
  seed_top_k: [256,256]
  seed_radius_coe: 0.01
  net_channels: 256
  layer_num: 9
  head: 4
  seedlayer: [0,6]
  use_mc_seeding: True
  use_score_encoding: True
  conf_bar: [1.11,0.1]
  sink_iter: [10,100]
  detach_iter: 1000000
  p_th: 0.2