defaults:
  - method: sp_sgm
  - dataset: sen1-2
  - _self_
hydra:
  sweeper:
    params:
      method: d2,d2-mnn,d2-magsac,dh
      dataset: osdataset,sen1-2,whu-sen-city
  sweep:
    dir: log/multirun/${method.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${dataset.name}
  run:
    dir: log/${method.name}
  