defaults:
  - extractor: d2
  - matcher: bf
  - ransac: magsacpp
  - dataset: osdataset
  - _self_

hydra:
  sweeper:
    params:
      dataset: osdataset,sen1-2,whu-sen-city
  sweep:
    dir: log/multirun/${extractor.name}_${matcher.name}_${ransac.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${dataset.name}
  run:
    dir: log/${extractor.name}_${matcher.name}_${ransac.name}
  